using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Xml;
using ZatcaIntegrationSDK.GeneralLogic;
using ZatcaIntegrationSDK;

namespace SimpleInvoice
{
    public partial class GeneratePDFA3 : Form
    {
        public GeneratePDFA3()
        {
            InitializeComponent();
        }

        private void btnpdfa3_Click(object sender, EventArgs e)
        {
            if (!File.Exists(txt_xmlpath.Text))
            {
                MessageBox.Show("Can not load XML file");
                return;
            }
            if (!File.Exists(txt_pdfpath.Text))
            {
                MessageBox.Show("Can not load PDF file");
                return;
            }

            PDFA3Result pdfresult = new PDFA3Result();
            XMLPDF xMLPDF = new XMLPDF();
            pdfresult = xMLPDF.ConvertXMLToPDFA3ByteArray(txt_xmlpath.Text, txt_pdfpath.Text);
            //pdfresult = xMLPDF.ConvertEncodedXMLToPDFA3ByteArray(@"DQo8SW52b2ljZSB4bWxucz0idXJuOm9hc2lzOm5hbWVzOnNwZWNpZmljYXRpb246dWJsOnNjaGVtYTp4c2Q6SW52b2ljZS0yIiB4bWxuczpjYWM9InVybjpvYXNpczpuYW1lczpzcGVjaWZpY2F0aW9uOnVibDpzY2hlbWE6eHNkOkNvbW1vbkFnZ3JlZ2F0ZUNvbXBvbmVudHMtMiIgeG1sbnM6Y2JjPSJ1cm46b2FzaXM6bmFtZXM6c3BlY2lmaWNhdGlvbjp1Ymw6c2NoZW1hOnhzZDpDb21tb25CYXNpY0NvbXBvbmVudHMtMiIgeG1sbnM6ZXh0PSJ1cm46b2FzaXM6bmFtZXM6c3BlY2lmaWNhdGlvbjp1Ymw6c2NoZW1hOnhzZDpDb21tb25FeHRlbnNpb25Db21wb25lbnRzLTIiPjxleHQ6VUJMRXh0ZW5zaW9ucz4NCiAgICA8ZXh0OlVCTEV4dGVuc2lvbj4NCiAgICAgICAgPGV4dDpFeHRlbnNpb25VUkk+dXJuOm9hc2lzOm5hbWVzOnNwZWNpZmljYXRpb246dWJsOmRzaWc6ZW52ZWxvcGVkOnhhZGVzPC9leHQ6RXh0ZW5zaW9uVVJJPg0KICAgICAgICA8ZXh0OkV4dGVuc2lvbkNvbnRlbnQ+DQogICAgICAgICAgICA8IS0tIFBsZWFzZSBub3RlIHRoYXQgdGhlIHNpZ25hdHVyZSB2YWx1ZXMgYXJlIHNhbXBsZSB2YWx1ZXMgb25seSAtLT4NCiAgICAgICAgICAgIDxzaWc6VUJMRG9jdW1lbnRTaWduYXR1cmVzIHhtbG5zOnNpZz0idXJuOm9hc2lzOm5hbWVzOnNwZWNpZmljYXRpb246dWJsOnNjaGVtYTp4c2Q6Q29tbW9uU2lnbmF0dXJlQ29tcG9uZW50cy0yIiB4bWxuczpzYWM9InVybjpvYXNpczpuYW1lczpzcGVjaWZpY2F0aW9uOnVibDpzY2hlbWE6eHNkOlNpZ25hdHVyZUFnZ3JlZ2F0ZUNvbXBvbmVudHMtMiIgeG1sbnM6c2JjPSJ1cm46b2FzaXM6bmFtZXM6c3BlY2lmaWNhdGlvbjp1Ymw6c2NoZW1hOnhzZDpTaWduYXR1cmVCYXNpY0NvbXBvbmVudHMtMiI+DQogICAgICAgICAgICAgICAgPHNhYzpTaWduYXR1cmVJbmZvcm1hdGlvbj4NCiAgICAgICAgICAgICAgICAgICAgPGNiYzpJRD51cm46b2FzaXM6bmFtZXM6c3BlY2lmaWNhdGlvbjp1Ymw6c2lnbmF0dXJlOjE8L2NiYzpJRD4NCiAgICAgICAgICAgICAgICAgICAgPHNiYzpSZWZlcmVuY2VkU2lnbmF0dXJlSUQ+dXJuOm9hc2lzOm5hbWVzOnNwZWNpZmljYXRpb246dWJsOnNpZ25hdHVyZTpJbnZvaWNlPC9zYmM6UmVmZXJlbmNlZFNpZ25hdHVyZUlEPg0KICAgICAgICAgICAgICAgICAgICA8ZHM6U2lnbmF0dXJlIElkPSJzaWduYXR1cmUiIHhtbG5zOmRzPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjIj4NCiAgICAgICAgICAgICAgICAgICAgICAgIDxkczpTaWduZWRJbmZvPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxkczpDYW5vbmljYWxpemF0aW9uTWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwNi8xMi94bWwtYzE0bjExIiAvPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxkczpTaWduYXR1cmVNZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNlY2RzYS1zaGEyNTYiIC8+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgPGRzOlJlZmVyZW5jZSBJZD0iaW52b2ljZVNpZ25lZERhdGEiIFVSST0iIj4NCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGRzOlRyYW5zZm9ybXM+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8ZHM6VHJhbnNmb3JtIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvVFIvMTk5OS9SRUMteHBhdGgtMTk5OTExMTYiPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxkczpYUGF0aD5ub3QoLy9hbmNlc3Rvci1vci1zZWxmOjpleHQ6VUJMRXh0ZW5zaW9ucyk8L2RzOlhQYXRoPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9kczpUcmFuc2Zvcm0+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8ZHM6VHJhbnNmb3JtIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvVFIvMTk5OS9SRUMteHBhdGgtMTk5OTExMTYiPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxkczpYUGF0aD5ub3QoLy9hbmNlc3Rvci1vci1zZWxmOjpjYWM6U2lnbmF0dXJlKTwvZHM6WFBhdGg+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2RzOlRyYW5zZm9ybT4NCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxkczpUcmFuc2Zvcm0gQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy9UUi8xOTk5L1JFQy14cGF0aC0xOTk5MTExNiI+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGRzOlhQYXRoPm5vdCgvL2FuY2VzdG9yLW9yLXNlbGY6OmNhYzpBZGRpdGlvbmFsRG9jdW1lbnRSZWZlcmVuY2VbY2JjOklEPSdRUiddKTwvZHM6WFBhdGg+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2RzOlRyYW5zZm9ybT4NCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxkczpUcmFuc2Zvcm0gQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDA2LzEyL3htbC1jMTRuMTEiIC8+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvZHM6VHJhbnNmb3Jtcz4NCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGRzOkRpZ2VzdE1ldGhvZCBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMDQveG1sZW5jI3NoYTI1NiIgLz4NCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGRzOkRpZ2VzdFZhbHVlPkZpUmU4SUd4V1RZVWRZMkJENjBHSWdZQ2F6TDJuMkh5MVJhTllEMEw5NkU9PC9kczpEaWdlc3RWYWx1ZT4NCiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2RzOlJlZmVyZW5jZT4NCiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8ZHM6UmVmZXJlbmNlIFR5cGU9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyNTaWduYXR1cmVQcm9wZXJ0aWVzIiBVUkk9IiN4YWRlc1NpZ25lZFByb3BlcnRpZXMiPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8ZHM6RGlnZXN0TWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8wNC94bWxlbmMjc2hhMjU2IiAvPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8ZHM6RGlnZXN0VmFsdWU+TVdWbVpXUm1NamxtT0dZNVpqSTFNRFZoTkRJek0yUm1OREV3WldZME5EWmxabVZpTmpkbVl6RmlPVGt4T1RZeU5EazRaakJoTkRrNE5HWTFZemxrTVE9PTwvZHM6RGlnZXN0VmFsdWU+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9kczpSZWZlcmVuY2U+DQogICAgICAgICAgICAgICAgICAgICAgICA8L2RzOlNpZ25lZEluZm8+DQogICAgICAgICAgICAgICAgICAgICAgICA8ZHM6U2lnbmF0dXJlVmFsdWU+TUVZQ0lRQ3QxbmVNK2hadzMxbW9XYjBHU3JoV3k2cktKVkJvQ1JyaHBwTlNvRldrZVFJaEFLbmtlMUxUL0k5cnllTWc5NmZ1eDk3T0tVVW0vdkF1UUszc1pNWDB6R3JNPC9kczpTaWduYXR1cmVWYWx1ZT4NCiAgICAgICAgICAgICAgICAgICAgICAgIDxkczpLZXlJbmZvPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxkczpYNTA5RGF0YT4NCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGRzOlg1MDlDZXJ0aWZpY2F0ZT5NSUlEOWpDQ0E1dWdBd0lCQWdJVGJ3QUFlQ3k5YUtjTEE5OUhyQUFCQUFCNExEQUtCZ2dxaGtqT1BRUURBakJqTVJVd0V3WUtDWkltaVpQeUxHUUJHUllGYkc5allXd3hFekFSQmdvSmtpYUprL0lzWkFFWkZnTm5iM1l4RnpBVkJnb0praWFKay9Jc1pBRVpGZ2RsZUhSbllYcDBNUnd3R2dZRFZRUURFeE5VVTFwRlNVNVdUMGxEUlMxVGRXSkRRUzB4TUI0WERUSXlNRFF4T1RJd05Ea3dPVm9YRFRJME1EUXhPREl3TkRrd09Wb3dXVEVMTUFrR0ExVUVCaE1DVTBFeEV6QVJCZ05WQkFvVENqTXhNak0wTlRZM09Ea3hEREFLQmdOVkJBc1RBMVJUVkRFbk1DVUdBMVVFQXhNZVZGTlVMUzA1TnpBMU5qQXdOREF0TXpFeU16UTFOamM0T1RBd01EQXpNRll3RUFZSEtvWkl6ajBDQVFZRks0RUVBQW9EUWdBRVlZTU1vT2FGWUFoTU8vc3Rlb3RmWnlhdnI2cDExU1Nsd3NLOWF6bXNMWTdiMWIrRkxocU1BcmhCMmRxSEtib3hxS05mdmtLRGVQaHBxanVpNWhjbjBhT0NBamt3Z2dJMU1JR2FCZ05WSFJFRWdaSXdnWStrZ1l3d2dZa3hPekE1QmdOVkJBUU1NakV0VkZOVWZESXRWRk5VZkRNdE5EZG1NVFpqTWpZdE9EQTJZaTAwWlRFMUxXSXlOamt0TjJFNE1ETTRPRFJpWlRsak1SOHdIUVlLQ1pJbWlaUHlMR1FCQVF3UE16RXlNelExTmpjNE9UQXdNREF6TVEwd0N3WURWUVFNREFReE1UQXdNUXd3Q2dZRFZRUWFEQU5VVTFReEREQUtCZ05WQkE4TUExUlRWREFkQmdOVkhRNEVGZ1FVTzVaaVU3TmFrVTNlZWpWYTNJMlMxQjJzRHdrd0h3WURWUjBqQkJnd0ZvQVVkbUNNK3dhZ3JHZFhOWjNQbXF5bks1azF0Uzh3VGdZRFZSMGZCRWN3UlRCRG9FR2dQNFk5YUhSMGNEb3ZMM1J6ZEdOeWJDNTZZWFJqWVM1bmIzWXVjMkV2UTJWeWRFVnVjbTlzYkM5VVUxcEZTVTVXVDBsRFJTMVRkV0pEUVMweExtTnliRENCclFZSUt3WUJCUVVIQVFFRWdhQXdnWjB3YmdZSUt3WUJCUVVITUFHR1ltaDBkSEE2THk5MGMzUmpjbXd1ZW1GMFkyRXVaMjkyTG5OaEwwTmxjblJGYm5KdmJHd3ZWRk5hUldsdWRtOXBZMlZUUTBFeExtVjRkR2RoZW5RdVoyOTJMbXh2WTJGc1gxUlRXa1ZKVGxaUFNVTkZMVk4xWWtOQkxURW9NU2t1WTNKME1Dc0dDQ3NHQVFVRkJ6QUJoaDlvZEhSd09pOHZkSE4wWTNKc0xucGhkR05oTG1kdmRpNXpZUzl2WTNOd01BNEdBMVVkRHdFQi93UUVBd0lIZ0RBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFnWUlLd1lCQlFVSEF3TXdKd1lKS3dZQkJBR0NOeFVLQkJvd0dEQUtCZ2dyQmdFRkJRY0RBakFLQmdnckJnRUZCUWNEQXpBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQTdtSFQ2eWc4NWp0UUdXcDNNN3RQVDdKazIrenN2VkhHczNiVTVaN1lFNjhDSVFENjBlYlFhbVlqWXZkZWJuRmpOZng0WDRkb3A3THNFQkZDTlNzTFkwSUZhUT09PC9kczpYNTA5Q2VydGlmaWNhdGU+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9kczpYNTA5RGF0YT4NCiAgICAgICAgICAgICAgICAgICAgICAgIDwvZHM6S2V5SW5mbz4NCiAgICAgICAgICAgICAgICAgICAgICAgIDxkczpPYmplY3Q+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgPHhhZGVzOlF1YWxpZnlpbmdQcm9wZXJ0aWVzIFRhcmdldD0ic2lnbmF0dXJlIiB4bWxuczp4YWRlcz0iaHR0cDovL3VyaS5ldHNpLm9yZy8wMTkwMy92MS4zLjIjIj4NCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHhhZGVzOlNpZ25lZFByb3BlcnRpZXMgSWQ9InhhZGVzU2lnbmVkUHJvcGVydGllcyI+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8eGFkZXM6U2lnbmVkU2lnbmF0dXJlUHJvcGVydGllcz4NCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8eGFkZXM6U2lnbmluZ1RpbWU+MjAyNC0wNS0wN1QxNzoxNjozOTwveGFkZXM6U2lnbmluZ1RpbWU+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHhhZGVzOlNpZ25pbmdDZXJ0aWZpY2F0ZT4NCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHhhZGVzOkNlcnQ+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8eGFkZXM6Q2VydERpZ2VzdD4NCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8ZHM6RGlnZXN0TWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8wNC94bWxlbmMjc2hhMjU2IiAvPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxkczpEaWdlc3RWYWx1ZT5OamxoT1RWbVl6SXpOMkkwTWpjeE5HUmpORFExTjJFek0ySTVOR05qTkRVeVptUTVaakV4TURVd05HTTJPRE5qTkRBeE1UUTBaRGsxTkRRNE9UUm1ZZz09PC9kczpEaWdlc3RWYWx1ZT4NCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwveGFkZXM6Q2VydERpZ2VzdD4NCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDx4YWRlczpJc3N1ZXJTZXJpYWw+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGRzOlg1MDlJc3N1ZXJOYW1lPkNOPVRTWkVJTlZPSUNFLVN1YkNBLTEsIERDPWV4dGdhenQsIERDPWdvdiwgREM9bG9jYWw8L2RzOlg1MDlJc3N1ZXJOYW1lPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxkczpYNTA5U2VyaWFsTnVtYmVyPjI0NzUzODI4NzY3NzY1NjEzOTE1MTcyMDY2NTE2NDU2NjAyNzk0NjI3MjE1ODA8L2RzOlg1MDlTZXJpYWxOdW1iZXI+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L3hhZGVzOklzc3VlclNlcmlhbD4NCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPC94YWRlczpDZXJ0Pg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwveGFkZXM6U2lnbmluZ0NlcnRpZmljYXRlPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPC94YWRlczpTaWduZWRTaWduYXR1cmVQcm9wZXJ0aWVzPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L3hhZGVzOlNpZ25lZFByb3BlcnRpZXM+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgPC94YWRlczpRdWFsaWZ5aW5nUHJvcGVydGllcz4NCiAgICAgICAgICAgICAgICAgICAgICAgIDwvZHM6T2JqZWN0Pg0KICAgICAgICAgICAgICAgICAgICA8L2RzOlNpZ25hdHVyZT4NCiAgICAgICAgICAgICAgICA8L3NhYzpTaWduYXR1cmVJbmZvcm1hdGlvbj4NCiAgICAgICAgICAgIDwvc2lnOlVCTERvY3VtZW50U2lnbmF0dXJlcz4NCiAgICAgICAgPC9leHQ6RXh0ZW5zaW9uQ29udGVudD4NCiAgICA8L2V4dDpVQkxFeHRlbnNpb24+DQo8L2V4dDpVQkxFeHRlbnNpb25zPg0KICA8Y2JjOlByb2ZpbGVJRD5yZXBvcnRpbmc6MS4wPC9jYmM6UHJvZmlsZUlEPg0KICA8Y2JjOklEPkludi0yMzQ8L2NiYzpJRD4NCiAgPGNiYzpVVUlEPmYzMGI5NTIyLWJkZDQtNGM1ZC1iZjViLTEwY2JlZDAyZWY4MDwvY2JjOlVVSUQ+DQogIDxjYmM6SXNzdWVEYXRlPjIwMjQtMDUtMDc8L2NiYzpJc3N1ZURhdGU+DQogIDxjYmM6SXNzdWVUaW1lPjE3OjE2OjIyPC9jYmM6SXNzdWVUaW1lPg0KICA8Y2JjOkludm9pY2VUeXBlQ29kZSBuYW1lPSIwMjAwMDAwIj4zODg8L2NiYzpJbnZvaWNlVHlwZUNvZGU+DQogIDxjYmM6RG9jdW1lbnRDdXJyZW5jeUNvZGU+U0FSPC9jYmM6RG9jdW1lbnRDdXJyZW5jeUNvZGU+DQogIDxjYmM6VGF4Q3VycmVuY3lDb2RlPlNBUjwvY2JjOlRheEN1cnJlbmN5Q29kZT4NCiAgPGNiYzpMaW5lQ291bnROdW1lcmljPjE8L2NiYzpMaW5lQ291bnROdW1lcmljPg0KICA8Y2FjOkFkZGl0aW9uYWxEb2N1bWVudFJlZmVyZW5jZT4NCiAgICA8Y2JjOklEPklDVjwvY2JjOklEPg0KICAgIDxjYmM6VVVJRD4yMzQ8L2NiYzpVVUlEPg0KICA8L2NhYzpBZGRpdGlvbmFsRG9jdW1lbnRSZWZlcmVuY2U+DQogIDxjYWM6QWRkaXRpb25hbERvY3VtZW50UmVmZXJlbmNlPg0KICAgIDxjYmM6SUQ+UElIPC9jYmM6SUQ+DQogICAgPGNhYzpBdHRhY2htZW50Pg0KICAgICAgPGNiYzpFbWJlZGRlZERvY3VtZW50QmluYXJ5T2JqZWN0IG1pbWVDb2RlPSJ0ZXh0L3BsYWluIj5OV1psWTJWaU5qWm1abU00Tm1Zek9HUTVOVEkzT0Raak5tUTJPVFpqTnpsak1tUmlZekl6T1dSa05HVTVNV0kwTmpjeU9XUTNNMkV5TjJaaU5UZGxPUT09PC9jYmM6RW1iZWRkZWREb2N1bWVudEJpbmFyeU9iamVjdD4NCiAgICA8L2NhYzpBdHRhY2htZW50Pg0KICA8L2NhYzpBZGRpdGlvbmFsRG9jdW1lbnRSZWZlcmVuY2U+DQogIDxjYWM6QWRkaXRpb25hbERvY3VtZW50UmVmZXJlbmNlPg0KICAgICAgICA8Y2JjOklEPlFSPC9jYmM6SUQ+DQogICAgICAgIDxjYWM6QXR0YWNobWVudD4NCiAgICAgICAgICAgIDxjYmM6RW1iZWRkZWREb2N1bWVudEJpbmFyeU9iamVjdCBtaW1lQ29kZT0idGV4dC9wbGFpbiI+QVF4MFpYTjBJR052YlhCaGJua0NEek13TURBMU5UazRORGN3TURBd013TVRNakF5TkMwd05TMHdOMVF4TnpveE5qb3lNZ1FHTVRFMUxqQXdCUVV4TlM0d01BWXNSbWxTWlRoSlIzaFhWRmxWWkZreVFrUTJNRWRKWjFsRFlYcE1NbTR5U0hreFVtRk9XVVF3VERrMlJUMEhZRTFGV1VOSlVVTjBNVzVsVFN0b1duY3pNVzF2VjJJd1IxTnlhRmQ1Tm5KTFNsWkNiME5TY21od2NFNVRiMFpYYTJWUlNXaEJTMjVyWlRGTVZDOUpPWEo1WlUxbk9UWm1kWGc1TjA5TFZWVnRMM1pCZFZGTE0zTmFUVmd3ZWtkeVRRaFlNRll3RUFZSEtvWkl6ajBDQVFZRks0RUVBQW9EUWdBRVlZTU1vT2FGWUFoTU8vc3Rlb3RmWnlhdnI2cDExU1Nsd3NLOWF6bXNMWTdiMWIrRkxocU1BcmhCMmRxSEtib3hxS05mdmtLRGVQaHBxanVpNWhjbjBRbElNRVlDSVFEdVlkUHJLRHptTzFBWmFuY3p1MDlQc21UYjdPeTlVY2F6ZHRUbG50Z1Ryd0loQVByUjV0QnFaaU5pOTE1dWNXTTEvSGhmaDJpbnN1d1FFVUkxS3d0alFnVnA8L2NiYzpFbWJlZGRlZERvY3VtZW50QmluYXJ5T2JqZWN0Pg0KICAgICAgICA8L2NhYzpBdHRhY2htZW50Pg0KPC9jYWM6QWRkaXRpb25hbERvY3VtZW50UmVmZXJlbmNlPjxjYWM6U2lnbmF0dXJlPgogICAgICA8Y2JjOklEPnVybjpvYXNpczpuYW1lczpzcGVjaWZpY2F0aW9uOnVibDpzaWduYXR1cmU6SW52b2ljZTwvY2JjOklEPgogICAgICA8Y2JjOlNpZ25hdHVyZU1ldGhvZD51cm46b2FzaXM6bmFtZXM6c3BlY2lmaWNhdGlvbjp1Ymw6ZHNpZzplbnZlbG9wZWQ6eGFkZXM8L2NiYzpTaWduYXR1cmVNZXRob2Q+CjwvY2FjOlNpZ25hdHVyZT48Y2FjOkFjY291bnRpbmdTdXBwbGllclBhcnR5Pg0KICAgIDxjYWM6UGFydHk+DQogICAgICA8Y2FjOlBhcnR5SWRlbnRpZmljYXRpb24+DQogICAgICAgIDxjYmM6SUQgc2NoZW1lSUQ9IkNSTiI+MTIzNDU2PC9jYmM6SUQ+DQogICAgICA8L2NhYzpQYXJ0eUlkZW50aWZpY2F0aW9uPg0KICAgICAgPGNhYzpQb3N0YWxBZGRyZXNzPg0KICAgICAgICA8Y2JjOlN0cmVldE5hbWU+c3RyZWV0IG5hbWU8L2NiYzpTdHJlZXROYW1lPg0KICAgICAgICA8Y2JjOkJ1aWxkaW5nTnVtYmVyPjM3MjQ8L2NiYzpCdWlsZGluZ051bWJlcj4NCiAgICAgICAgPGNiYzpDaXR5U3ViZGl2aXNpb25OYW1lPkFsZmFsYWg8L2NiYzpDaXR5U3ViZGl2aXNpb25OYW1lPg0KICAgICAgICA8Y2JjOkNpdHlOYW1lPnRhaWY8L2NiYzpDaXR5TmFtZT4NCiAgICAgICAgPGNiYzpQb3N0YWxab25lPjE1Mzg1PC9jYmM6UG9zdGFsWm9uZT4NCiAgICAgICAgPGNhYzpDb3VudHJ5Pg0KICAgICAgICAgIDxjYmM6SWRlbnRpZmljYXRpb25Db2RlPlNBPC9jYmM6SWRlbnRpZmljYXRpb25Db2RlPg0KICAgICAgICA8L2NhYzpDb3VudHJ5Pg0KICAgICAgPC9jYWM6UG9zdGFsQWRkcmVzcz4NCiAgICAgIDxjYWM6UGFydHlUYXhTY2hlbWU+DQogICAgICAgIDxjYmM6Q29tcGFueUlEPjMwMDA1NTk4NDcwMDAwMzwvY2JjOkNvbXBhbnlJRD4NCiAgICAgICAgPGNhYzpUYXhTY2hlbWU+DQogICAgICAgICAgPGNiYzpJRD5WQVQ8L2NiYzpJRD4NCiAgICAgICAgPC9jYWM6VGF4U2NoZW1lPg0KICAgICAgPC9jYWM6UGFydHlUYXhTY2hlbWU+DQogICAgICA8Y2FjOlBhcnR5TGVnYWxFbnRpdHk+DQogICAgICAgIDxjYmM6UmVnaXN0cmF0aW9uTmFtZT50ZXN0IGNvbXBhbnk8L2NiYzpSZWdpc3RyYXRpb25OYW1lPg0KICAgICAgPC9jYWM6UGFydHlMZWdhbEVudGl0eT4NCiAgICA8L2NhYzpQYXJ0eT4NCiAgPC9jYWM6QWNjb3VudGluZ1N1cHBsaWVyUGFydHk+DQogIDxjYWM6QWNjb3VudGluZ0N1c3RvbWVyUGFydHk+DQogICAgPGNhYzpQYXJ0eT4NCiAgICAgIDxjYWM6UGFydHlJZGVudGlmaWNhdGlvbj4NCiAgICAgICAgPGNiYzpJRCBzY2hlbWVJRD0iQ1JOIj4xMjM0NTY8L2NiYzpJRD4NCiAgICAgIDwvY2FjOlBhcnR5SWRlbnRpZmljYXRpb24+DQogICAgICA8Y2FjOlBvc3RhbEFkZHJlc3M+DQogICAgICAgIDxjYmM6U3RyZWV0TmFtZT5zdHJlZXQgbmFtZTwvY2JjOlN0cmVldE5hbWU+DQogICAgICAgIDxjYmM6QnVpbGRpbmdOdW1iZXI+MzcyNDwvY2JjOkJ1aWxkaW5nTnVtYmVyPg0KICAgICAgICA8Y2JjOkNpdHlTdWJkaXZpc2lvbk5hbWU+QWxmYWxhaDwvY2JjOkNpdHlTdWJkaXZpc2lvbk5hbWU+DQogICAgICAgIDxjYmM6Q2l0eU5hbWU+SmVkZGFoPC9jYmM6Q2l0eU5hbWU+DQogICAgICAgIDxjYmM6UG9zdGFsWm9uZT4xNTM4NTwvY2JjOlBvc3RhbFpvbmU+DQogICAgICAgIDxjYWM6Q291bnRyeT4NCiAgICAgICAgICA8Y2JjOklkZW50aWZpY2F0aW9uQ29kZT5TQTwvY2JjOklkZW50aWZpY2F0aW9uQ29kZT4NCiAgICAgICAgPC9jYWM6Q291bnRyeT4NCiAgICAgIDwvY2FjOlBvc3RhbEFkZHJlc3M+DQogICAgICA8Y2FjOlBhcnR5VGF4U2NoZW1lPg0KICAgICAgICA8Y2JjOkNvbXBhbnlJRD4zMTA0MjQ0MTUwMDAwMDM8L2NiYzpDb21wYW55SUQ+DQogICAgICAgIDxjYWM6VGF4U2NoZW1lPg0KICAgICAgICAgIDxjYmM6SUQ+VkFUPC9jYmM6SUQ+DQogICAgICAgIDwvY2FjOlRheFNjaGVtZT4NCiAgICAgIDwvY2FjOlBhcnR5VGF4U2NoZW1lPg0KICAgICAgPGNhYzpQYXJ0eUxlZ2FsRW50aXR5Pg0KICAgICAgICA8Y2JjOlJlZ2lzdHJhdGlvbk5hbWU+2YXYpNiz2LPYqSDYp9mE2YXYtNiq2LHZiTwvY2JjOlJlZ2lzdHJhdGlvbk5hbWU+DQogICAgICA8L2NhYzpQYXJ0eUxlZ2FsRW50aXR5Pg0KICAgIDwvY2FjOlBhcnR5Pg0KICA8L2NhYzpBY2NvdW50aW5nQ3VzdG9tZXJQYXJ0eT4NCiAgPGNhYzpQYXltZW50TWVhbnM+DQogICAgPGNiYzpQYXltZW50TWVhbnNDb2RlPjEwPC9jYmM6UGF5bWVudE1lYW5zQ29kZT4NCiAgPC9jYWM6UGF5bWVudE1lYW5zPg0KICA8Y2FjOlRheFRvdGFsPg0KICAgIDxjYmM6VGF4QW1vdW50IGN1cnJlbmN5SUQ9IlNBUiI+MTUuMDA8L2NiYzpUYXhBbW91bnQ+DQogICAgPGNhYzpUYXhTdWJ0b3RhbD4NCiAgICAgIDxjYmM6VGF4YWJsZUFtb3VudCBjdXJyZW5jeUlEPSJTQVIiPjEwMC4wMDwvY2JjOlRheGFibGVBbW91bnQ+DQogICAgICA8Y2JjOlRheEFtb3VudCBjdXJyZW5jeUlEPSJTQVIiPjE1LjAwPC9jYmM6VGF4QW1vdW50Pg0KICAgICAgPGNhYzpUYXhDYXRlZ29yeT4NCiAgICAgICAgPGNiYzpJRD5TPC9jYmM6SUQ+DQogICAgICAgIDxjYmM6UGVyY2VudD4xNS4wMDwvY2JjOlBlcmNlbnQ+DQogICAgICAgIDxjYWM6VGF4U2NoZW1lPg0KICAgICAgICAgIDxjYmM6SUQ+VkFUPC9jYmM6SUQ+DQogICAgICAgIDwvY2FjOlRheFNjaGVtZT4NCiAgICAgIDwvY2FjOlRheENhdGVnb3J5Pg0KICAgIDwvY2FjOlRheFN1YnRvdGFsPg0KICA8L2NhYzpUYXhUb3RhbD4NCiAgPGNhYzpUYXhUb3RhbD4NCiAgICA8Y2JjOlRheEFtb3VudCBjdXJyZW5jeUlEPSJTQVIiPjE1LjAwPC9jYmM6VGF4QW1vdW50Pg0KICA8L2NhYzpUYXhUb3RhbD4NCiAgPGNhYzpMZWdhbE1vbmV0YXJ5VG90YWw+DQogICAgPGNiYzpMaW5lRXh0ZW5zaW9uQW1vdW50IGN1cnJlbmN5SUQ9IlNBUiI+MTAwLjAwPC9jYmM6TGluZUV4dGVuc2lvbkFtb3VudD4NCiAgICA8Y2JjOlRheEV4Y2x1c2l2ZUFtb3VudCBjdXJyZW5jeUlEPSJTQVIiPjEwMC4wMDwvY2JjOlRheEV4Y2x1c2l2ZUFtb3VudD4NCiAgICA8Y2JjOlRheEluY2x1c2l2ZUFtb3VudCBjdXJyZW5jeUlEPSJTQVIiPjExNS4wMDwvY2JjOlRheEluY2x1c2l2ZUFtb3VudD4NCiAgICA8Y2JjOkFsbG93YW5jZVRvdGFsQW1vdW50IGN1cnJlbmN5SUQ9IlNBUiI+MC4wMDwvY2JjOkFsbG93YW5jZVRvdGFsQW1vdW50Pg0KICAgIDxjYmM6Q2hhcmdlVG90YWxBbW91bnQgY3VycmVuY3lJRD0iU0FSIj4wLjAwPC9jYmM6Q2hhcmdlVG90YWxBbW91bnQ+DQogICAgPGNiYzpQYXlhYmxlQW1vdW50IGN1cnJlbmN5SUQ9IlNBUiI+MTE1LjAwPC9jYmM6UGF5YWJsZUFtb3VudD4NCiAgPC9jYWM6TGVnYWxNb25ldGFyeVRvdGFsPg0KICA8Y2FjOkludm9pY2VMaW5lPg0KICAgIDxjYmM6SUQ+MTwvY2JjOklEPg0KICAgIDxjYmM6SW52b2ljZWRRdWFudGl0eT4xMDwvY2JjOkludm9pY2VkUXVhbnRpdHk+DQogICAgPGNiYzpMaW5lRXh0ZW5zaW9uQW1vdW50IGN1cnJlbmN5SUQ9IlNBUiI+MTAwLjAwPC9jYmM6TGluZUV4dGVuc2lvbkFtb3VudD4NCiAgICA8Y2FjOlRheFRvdGFsPg0KICAgICAgPGNiYzpUYXhBbW91bnQgY3VycmVuY3lJRD0iU0FSIj4xNS4wMDwvY2JjOlRheEFtb3VudD4NCiAgICAgIDxjYmM6Um91bmRpbmdBbW91bnQgY3VycmVuY3lJRD0iU0FSIj4xMTUuMDA8L2NiYzpSb3VuZGluZ0Ftb3VudD4NCiAgICA8L2NhYzpUYXhUb3RhbD4NCiAgICA8Y2FjOkl0ZW0+DQogICAgICA8Y2JjOk5hbWU+a2RrZGs8L2NiYzpOYW1lPg0KICAgICAgPGNhYzpDbGFzc2lmaWVkVGF4Q2F0ZWdvcnk+DQogICAgICAgIDxjYmM6SUQ+UzwvY2JjOklEPg0KICAgICAgICA8Y2JjOlBlcmNlbnQ+MTUuMDA8L2NiYzpQZXJjZW50Pg0KICAgICAgICA8Y2FjOlRheFNjaGVtZT4NCiAgICAgICAgICA8Y2JjOklEPlZBVDwvY2JjOklEPg0KICAgICAgICA8L2NhYzpUYXhTY2hlbWU+DQogICAgICA8L2NhYzpDbGFzc2lmaWVkVGF4Q2F0ZWdvcnk+DQogICAgPC9jYWM6SXRlbT4NCiAgICA8Y2FjOlByaWNlPg0KICAgICAgPGNiYzpQcmljZUFtb3VudCBjdXJyZW5jeUlEPSJTQVIiPjEwPC9jYmM6UHJpY2VBbW91bnQ+DQogICAgICA8Y2JjOkJhc2VRdWFudGl0eT4xLjAwPC9jYmM6QmFzZVF1YW50aXR5Pg0KICAgIDwvY2FjOlByaWNlPg0KICA8L2NhYzpJbnZvaWNlTGluZT4NCjwvSW52b2ljZT4=", @"C:\Users\Administrator\Downloads\AFAQ\new_pdf\good_InvoicePDF-RGBinv_A4-1110000015-1-5-2024.pdf", @"C:\Users\Administrator\Downloads\AFAQ\new_pdf");
            if (pdfresult.IsValid)
            {
               // MessageBox.Show("File Saved Successfuly at ");
                if (pdfresult.PDFA3ContentFile != null && pdfresult.PDFA3ContentFile.Length > 0)
                {
                    try
                    {
                        saveFileDialog1.Filter = "pdf files (*.pdf)|*.pdf";
                        saveFileDialog1.FileName = "InvoicePDFA3.pdf";
                        DialogResult resultdiag = saveFileDialog1.ShowDialog();

                        if (resultdiag == DialogResult.OK)
                        {
                            File.WriteAllBytes(saveFileDialog1.FileName, pdfresult.PDFA3ContentFile);
                            MessageBox.Show("File Saved Successfuly at " + saveFileDialog1.FileName);
                        }
                    }
                    catch (Exception ex)
                    {
                        MessageBox.Show(ex.InnerException.ToString());
                    }

                }
                else
                {
                    MessageBox.Show("PDF-A3 Not Generated !");
                }

            }
            else
            {
                MessageBox.Show(pdfresult.ErrorMessage);
            }
        }

        private void btn_browse_xml_Click(object sender, EventArgs e)
        {
            try
            {
                OpenFileDialog dialog = new OpenFileDialog();
                dialog.Filter = "XML Files|*.xml";
                dialog.InitialDirectory = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
                dialog.Title = "Choose xml file !";

                if (dialog.ShowDialog() == DialogResult.OK)
                {
                    if (!Path.GetExtension(dialog.FileName).ToLower().Contains(".xml"))
                        txt_xmlpath.Text = "You must choose xml file !";
                    else
                    {
                        txt_xmlpath.Text = dialog.FileName;
                    }
                }
                else
                {
                    txt_xmlpath.Text = "You must choose xml file !";
                }
            }
            catch
            {
                MessageBox.Show("Error while import xml file.");
            }
        }

        private void btn_browse_pdf_Click(object sender, EventArgs e)
        {
            try
            {
                OpenFileDialog dialog = new OpenFileDialog();
                dialog.Filter = "PDF Files|*.pdf";
                dialog.InitialDirectory = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
                dialog.Title = "Choose pdf file !";

                if (dialog.ShowDialog() == DialogResult.OK)
                {
                    if (!Path.GetExtension(dialog.FileName).ToLower().Contains(".pdf"))
                        txt_pdfpath.Text = "You must choose pdf file !";
                    else
                    {
                        txt_pdfpath.Text = dialog.FileName;
                    }
                }
                else
                {
                    txt_pdfpath.Text = "You must choose pdf file !";
                }
            }
            catch
            {
                MessageBox.Show("Error while import pdf file.");
            }
        }
       
    }
}
