// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NabdSchool.DAL.Data;

#nullable disable

namespace NabdSchool.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251112162328_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NabdSchool.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("NabdSchool.Core.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("NabdSchool.Core.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ClassNumber")
                        .HasColumnType("int");

                    b.Property<string>("ClassTeacher")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GradeId", "ClassNumber")
                        .IsUnique();

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 30,
                            ClassName = "الفصل 1",
                            ClassNumber = 1,
                            GradeId = 1,
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 30,
                            ClassName = "الفصل 2",
                            ClassNumber = 2,
                            GradeId = 1,
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 30,
                            ClassName = "الفصل 3",
                            ClassNumber = 3,
                            GradeId = 1,
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 30,
                            ClassName = "الفصل 4",
                            ClassNumber = 4,
                            GradeId = 1,
                            IsActive = true
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 30,
                            ClassName = "الفصل 5",
                            ClassNumber = 5,
                            GradeId = 1,
                            IsActive = true
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 30,
                            ClassName = "الفصل 1",
                            ClassNumber = 1,
                            GradeId = 2,
                            IsActive = true
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 30,
                            ClassName = "الفصل 2",
                            ClassNumber = 2,
                            GradeId = 2,
                            IsActive = true
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 30,
                            ClassName = "الفصل 3",
                            ClassNumber = 3,
                            GradeId = 2,
                            IsActive = true
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 30,
                            ClassName = "الفصل 4",
                            ClassNumber = 4,
                            GradeId = 2,
                            IsActive = true
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 30,
                            ClassName = "الفصل 5",
                            ClassNumber = 5,
                            GradeId = 2,
                            IsActive = true
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 30,
                            ClassName = "الفصل 1",
                            ClassNumber = 1,
                            GradeId = 3,
                            IsActive = true
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 30,
                            ClassName = "الفصل 2",
                            ClassNumber = 2,
                            GradeId = 3,
                            IsActive = true
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 30,
                            ClassName = "الفصل 3",
                            ClassNumber = 3,
                            GradeId = 3,
                            IsActive = true
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 30,
                            ClassName = "الفصل 4",
                            ClassNumber = 4,
                            GradeId = 3,
                            IsActive = true
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 30,
                            ClassName = "الفصل 5",
                            ClassNumber = 5,
                            GradeId = 3,
                            IsActive = true
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 30,
                            ClassName = "الفصل 1",
                            ClassNumber = 1,
                            GradeId = 4,
                            IsActive = true
                        },
                        new
                        {
                            Id = 17,
                            Capacity = 30,
                            ClassName = "الفصل 2",
                            ClassNumber = 2,
                            GradeId = 4,
                            IsActive = true
                        },
                        new
                        {
                            Id = 18,
                            Capacity = 30,
                            ClassName = "الفصل 3",
                            ClassNumber = 3,
                            GradeId = 4,
                            IsActive = true
                        },
                        new
                        {
                            Id = 19,
                            Capacity = 30,
                            ClassName = "الفصل 4",
                            ClassNumber = 4,
                            GradeId = 4,
                            IsActive = true
                        },
                        new
                        {
                            Id = 20,
                            Capacity = 30,
                            ClassName = "الفصل 5",
                            ClassNumber = 5,
                            GradeId = 4,
                            IsActive = true
                        },
                        new
                        {
                            Id = 21,
                            Capacity = 30,
                            ClassName = "الفصل 1",
                            ClassNumber = 1,
                            GradeId = 5,
                            IsActive = true
                        },
                        new
                        {
                            Id = 22,
                            Capacity = 30,
                            ClassName = "الفصل 2",
                            ClassNumber = 2,
                            GradeId = 5,
                            IsActive = true
                        },
                        new
                        {
                            Id = 23,
                            Capacity = 30,
                            ClassName = "الفصل 3",
                            ClassNumber = 3,
                            GradeId = 5,
                            IsActive = true
                        },
                        new
                        {
                            Id = 24,
                            Capacity = 30,
                            ClassName = "الفصل 4",
                            ClassNumber = 4,
                            GradeId = 5,
                            IsActive = true
                        },
                        new
                        {
                            Id = 25,
                            Capacity = 30,
                            ClassName = "الفصل 5",
                            ClassNumber = 5,
                            GradeId = 5,
                            IsActive = true
                        },
                        new
                        {
                            Id = 26,
                            Capacity = 30,
                            ClassName = "الفصل 1",
                            ClassNumber = 1,
                            GradeId = 6,
                            IsActive = true
                        },
                        new
                        {
                            Id = 27,
                            Capacity = 30,
                            ClassName = "الفصل 2",
                            ClassNumber = 2,
                            GradeId = 6,
                            IsActive = true
                        },
                        new
                        {
                            Id = 28,
                            Capacity = 30,
                            ClassName = "الفصل 3",
                            ClassNumber = 3,
                            GradeId = 6,
                            IsActive = true
                        },
                        new
                        {
                            Id = 29,
                            Capacity = 30,
                            ClassName = "الفصل 4",
                            ClassNumber = 4,
                            GradeId = 6,
                            IsActive = true
                        },
                        new
                        {
                            Id = 30,
                            Capacity = 30,
                            ClassName = "الفصل 5",
                            ClassNumber = 5,
                            GradeId = 6,
                            IsActive = true
                        },
                        new
                        {
                            Id = 31,
                            Capacity = 30,
                            ClassName = "الفصل 1",
                            ClassNumber = 1,
                            GradeId = 7,
                            IsActive = true
                        },
                        new
                        {
                            Id = 32,
                            Capacity = 30,
                            ClassName = "الفصل 2",
                            ClassNumber = 2,
                            GradeId = 7,
                            IsActive = true
                        },
                        new
                        {
                            Id = 33,
                            Capacity = 30,
                            ClassName = "الفصل 3",
                            ClassNumber = 3,
                            GradeId = 7,
                            IsActive = true
                        },
                        new
                        {
                            Id = 34,
                            Capacity = 30,
                            ClassName = "الفصل 4",
                            ClassNumber = 4,
                            GradeId = 7,
                            IsActive = true
                        },
                        new
                        {
                            Id = 35,
                            Capacity = 30,
                            ClassName = "الفصل 5",
                            ClassNumber = 5,
                            GradeId = 7,
                            IsActive = true
                        },
                        new
                        {
                            Id = 36,
                            Capacity = 30,
                            ClassName = "الفصل 1",
                            ClassNumber = 1,
                            GradeId = 8,
                            IsActive = true
                        },
                        new
                        {
                            Id = 37,
                            Capacity = 30,
                            ClassName = "الفصل 2",
                            ClassNumber = 2,
                            GradeId = 8,
                            IsActive = true
                        },
                        new
                        {
                            Id = 38,
                            Capacity = 30,
                            ClassName = "الفصل 3",
                            ClassNumber = 3,
                            GradeId = 8,
                            IsActive = true
                        },
                        new
                        {
                            Id = 39,
                            Capacity = 30,
                            ClassName = "الفصل 4",
                            ClassNumber = 4,
                            GradeId = 8,
                            IsActive = true
                        },
                        new
                        {
                            Id = 40,
                            Capacity = 30,
                            ClassName = "الفصل 5",
                            ClassNumber = 5,
                            GradeId = 8,
                            IsActive = true
                        },
                        new
                        {
                            Id = 41,
                            Capacity = 30,
                            ClassName = "الفصل 1",
                            ClassNumber = 1,
                            GradeId = 9,
                            IsActive = true
                        },
                        new
                        {
                            Id = 42,
                            Capacity = 30,
                            ClassName = "الفصل 2",
                            ClassNumber = 2,
                            GradeId = 9,
                            IsActive = true
                        },
                        new
                        {
                            Id = 43,
                            Capacity = 30,
                            ClassName = "الفصل 3",
                            ClassNumber = 3,
                            GradeId = 9,
                            IsActive = true
                        },
                        new
                        {
                            Id = 44,
                            Capacity = 30,
                            ClassName = "الفصل 4",
                            ClassNumber = 4,
                            GradeId = 9,
                            IsActive = true
                        },
                        new
                        {
                            Id = 45,
                            Capacity = 30,
                            ClassName = "الفصل 5",
                            ClassNumber = 5,
                            GradeId = 9,
                            IsActive = true
                        },
                        new
                        {
                            Id = 46,
                            Capacity = 30,
                            ClassName = "الفصل 1",
                            ClassNumber = 1,
                            GradeId = 10,
                            IsActive = true
                        },
                        new
                        {
                            Id = 47,
                            Capacity = 30,
                            ClassName = "الفصل 2",
                            ClassNumber = 2,
                            GradeId = 10,
                            IsActive = true
                        },
                        new
                        {
                            Id = 48,
                            Capacity = 30,
                            ClassName = "الفصل 3",
                            ClassNumber = 3,
                            GradeId = 10,
                            IsActive = true
                        },
                        new
                        {
                            Id = 49,
                            Capacity = 30,
                            ClassName = "الفصل 4",
                            ClassNumber = 4,
                            GradeId = 10,
                            IsActive = true
                        },
                        new
                        {
                            Id = 50,
                            Capacity = 30,
                            ClassName = "الفصل 5",
                            ClassNumber = 5,
                            GradeId = 10,
                            IsActive = true
                        },
                        new
                        {
                            Id = 51,
                            Capacity = 30,
                            ClassName = "الفصل 1",
                            ClassNumber = 1,
                            GradeId = 11,
                            IsActive = true
                        },
                        new
                        {
                            Id = 52,
                            Capacity = 30,
                            ClassName = "الفصل 2",
                            ClassNumber = 2,
                            GradeId = 11,
                            IsActive = true
                        },
                        new
                        {
                            Id = 53,
                            Capacity = 30,
                            ClassName = "الفصل 3",
                            ClassNumber = 3,
                            GradeId = 11,
                            IsActive = true
                        },
                        new
                        {
                            Id = 54,
                            Capacity = 30,
                            ClassName = "الفصل 4",
                            ClassNumber = 4,
                            GradeId = 11,
                            IsActive = true
                        },
                        new
                        {
                            Id = 55,
                            Capacity = 30,
                            ClassName = "الفصل 5",
                            ClassNumber = 5,
                            GradeId = 11,
                            IsActive = true
                        },
                        new
                        {
                            Id = 56,
                            Capacity = 30,
                            ClassName = "الفصل 1",
                            ClassNumber = 1,
                            GradeId = 12,
                            IsActive = true
                        },
                        new
                        {
                            Id = 57,
                            Capacity = 30,
                            ClassName = "الفصل 2",
                            ClassNumber = 2,
                            GradeId = 12,
                            IsActive = true
                        },
                        new
                        {
                            Id = 58,
                            Capacity = 30,
                            ClassName = "الفصل 3",
                            ClassNumber = 3,
                            GradeId = 12,
                            IsActive = true
                        },
                        new
                        {
                            Id = 59,
                            Capacity = 30,
                            ClassName = "الفصل 4",
                            ClassNumber = 4,
                            GradeId = 12,
                            IsActive = true
                        },
                        new
                        {
                            Id = 60,
                            Capacity = 30,
                            ClassName = "الفصل 5",
                            ClassNumber = 5,
                            GradeId = 12,
                            IsActive = true
                        });
                });

            modelBuilder.Entity("NabdSchool.Core.Entities.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GradeNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GradeNumber")
                        .IsUnique();

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GradeName = "الصف الأول",
                            GradeNumber = 1,
                            IsActive = true,
                            Stage = "ابتدائي"
                        },
                        new
                        {
                            Id = 2,
                            GradeName = "الصف الثاني",
                            GradeNumber = 2,
                            IsActive = true,
                            Stage = "ابتدائي"
                        },
                        new
                        {
                            Id = 3,
                            GradeName = "الصف الثالث",
                            GradeNumber = 3,
                            IsActive = true,
                            Stage = "ابتدائي"
                        },
                        new
                        {
                            Id = 4,
                            GradeName = "الصف الرابع",
                            GradeNumber = 4,
                            IsActive = true,
                            Stage = "ابتدائي"
                        },
                        new
                        {
                            Id = 5,
                            GradeName = "الصف الخامس",
                            GradeNumber = 5,
                            IsActive = true,
                            Stage = "ابتدائي"
                        },
                        new
                        {
                            Id = 6,
                            GradeName = "الصف السادس",
                            GradeNumber = 6,
                            IsActive = true,
                            Stage = "ابتدائي"
                        },
                        new
                        {
                            Id = 7,
                            GradeName = "الصف السابع",
                            GradeNumber = 7,
                            IsActive = true,
                            Stage = "متوسط"
                        },
                        new
                        {
                            Id = 8,
                            GradeName = "الصف الثامن",
                            GradeNumber = 8,
                            IsActive = true,
                            Stage = "متوسط"
                        },
                        new
                        {
                            Id = 9,
                            GradeName = "الصف التاسع",
                            GradeNumber = 9,
                            IsActive = true,
                            Stage = "متوسط"
                        },
                        new
                        {
                            Id = 10,
                            GradeName = "الصف العاشر",
                            GradeNumber = 10,
                            IsActive = true,
                            Stage = "ثانوي"
                        },
                        new
                        {
                            Id = 11,
                            GradeName = "الصف الحادي عشر",
                            GradeNumber = 11,
                            IsActive = true,
                            Stage = "ثانوي"
                        },
                        new
                        {
                            Id = 12,
                            GradeName = "الصف الثاني عشر",
                            GradeNumber = 12,
                            IsActive = true,
                            Stage = "ثانوي"
                        });
                });

            modelBuilder.Entity("NabdSchool.Core.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("GradeId");

                    b.HasIndex("IsVisible");

                    b.HasIndex("StudentNumber")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NabdSchool.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NabdSchool.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NabdSchool.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NabdSchool.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NabdSchool.Core.Entities.Class", b =>
                {
                    b.HasOne("NabdSchool.Core.Entities.Grade", "Grade")
                        .WithMany("Classes")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("NabdSchool.Core.Entities.Student", b =>
                {
                    b.HasOne("NabdSchool.Core.Entities.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NabdSchool.Core.Entities.Grade", "Grade")
                        .WithMany("Students")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("NabdSchool.Core.Entities.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("NabdSchool.Core.Entities.Grade", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
