// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesRepository.Data;

#nullable disable

namespace SalesRepository.Migrations
{
    [DbContext(typeof(SalesDBContext))]
    [Migration("20251126075401_AddBadgeSystem")]
    partial class AddBadgeSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SalesModel.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("SalesModel.Models.BadgeDefinition", b =>
                {
                    b.Property<int>("Definition_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Definition_ID"));

                    b.Property<string>("Badge_Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Badge_Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Badge_Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Badge_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Badge_Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("bit");

                    b.Property<int>("Required_Points")
                        .HasColumnType("int");

                    b.HasKey("Definition_ID");

                    b.ToTable("TblBadgeDefinitions");

                    b.HasData(
                        new
                        {
                            Definition_ID = 1,
                            Badge_Color = "#CD7F32",
                            Badge_Icon = "medal",
                            Badge_Level = "برونزي",
                            Badge_Name = "المنضبطة",
                            Badge_Type = "انضباط",
                            Created_Date = new DateTime(2025, 11, 26, 9, 54, 1, 210, DateTimeKind.Local).AddTicks(4561),
                            Description = "حضور منتظم لمدة أسبوعين",
                            Is_Active = true,
                            Required_Points = 50
                        },
                        new
                        {
                            Definition_ID = 2,
                            Badge_Color = "#C0C0C0",
                            Badge_Icon = "medal",
                            Badge_Level = "فضي",
                            Badge_Name = "المنضبطة",
                            Badge_Type = "انضباط",
                            Created_Date = new DateTime(2025, 11, 26, 9, 54, 1, 210, DateTimeKind.Local).AddTicks(4674),
                            Description = "حضور منتظم لمدة شهر",
                            Is_Active = true,
                            Required_Points = 150
                        },
                        new
                        {
                            Definition_ID = 3,
                            Badge_Color = "#FFD700",
                            Badge_Icon = "medal",
                            Badge_Level = "ذهبي",
                            Badge_Name = "المنضبطة",
                            Badge_Type = "انضباط",
                            Created_Date = new DateTime(2025, 11, 26, 9, 54, 1, 210, DateTimeKind.Local).AddTicks(4681),
                            Description = "حضور منتظم لمدة شهرين",
                            Is_Active = true,
                            Required_Points = 300
                        },
                        new
                        {
                            Definition_ID = 4,
                            Badge_Color = "#B9F2FF",
                            Badge_Icon = "medal",
                            Badge_Level = "ماسي",
                            Badge_Name = "المنضبطة",
                            Badge_Type = "انضباط",
                            Created_Date = new DateTime(2025, 11, 26, 9, 54, 1, 210, DateTimeKind.Local).AddTicks(4687),
                            Description = "حضور منتظم لمدة فصل كامل",
                            Is_Active = true,
                            Required_Points = 500
                        },
                        new
                        {
                            Definition_ID = 5,
                            Badge_Color = "#CD7F32",
                            Badge_Icon = "chart-simple",
                            Badge_Level = "برونزي",
                            Badge_Name = "المواظبة",
                            Badge_Type = "حضور_متتالي",
                            Created_Date = new DateTime(2025, 11, 26, 9, 54, 1, 210, DateTimeKind.Local).AddTicks(4692),
                            Description = "7 أيام حضور متتالي",
                            Is_Active = true,
                            Required_Points = 30
                        },
                        new
                        {
                            Definition_ID = 6,
                            Badge_Color = "#C0C0C0",
                            Badge_Icon = "chart-simple",
                            Badge_Level = "فضي",
                            Badge_Name = "المواظبة",
                            Badge_Type = "حضور_متتالي",
                            Created_Date = new DateTime(2025, 11, 26, 9, 54, 1, 210, DateTimeKind.Local).AddTicks(4697),
                            Description = "14 يوم حضور متتالي",
                            Is_Active = true,
                            Required_Points = 70
                        },
                        new
                        {
                            Definition_ID = 7,
                            Badge_Color = "#FFD700",
                            Badge_Icon = "chart-simple",
                            Badge_Level = "ذهبي",
                            Badge_Name = "المواظبة",
                            Badge_Type = "حضور_متتالي",
                            Created_Date = new DateTime(2025, 11, 26, 9, 54, 1, 210, DateTimeKind.Local).AddTicks(4702),
                            Description = "30 يوم حضور متتالي",
                            Is_Active = true,
                            Required_Points = 150
                        },
                        new
                        {
                            Definition_ID = 8,
                            Badge_Color = "#B9F2FF",
                            Badge_Icon = "chart-simple",
                            Badge_Level = "ماسي",
                            Badge_Name = "المواظبة",
                            Badge_Type = "حضور_متتالي",
                            Created_Date = new DateTime(2025, 11, 26, 9, 54, 1, 210, DateTimeKind.Local).AddTicks(4707),
                            Description = "60 يوم حضور متتالي",
                            Is_Active = true,
                            Required_Points = 300
                        });
                });

            modelBuilder.Entity("SalesModel.Models.StudentBadge", b =>
                {
                    b.Property<int>("Badge_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Badge_ID"));

                    b.Property<string>("Badge_Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Badge_Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Badge_Visible")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("Earned_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Student_ID")
                        .HasColumnType("int");

                    b.HasKey("Badge_ID");

                    b.HasIndex("Student_ID");

                    b.HasIndex("Badge_Type", "Badge_Level");

                    b.ToTable("TblStudentBadges");
                });

            modelBuilder.Entity("SalesModel.Models.StudentPoints", b =>
                {
                    b.Property<int>("Point_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Point_ID"));

                    b.Property<int>("Attendance_Streak")
                        .HasColumnType("int");

                    b.Property<DateTime>("Last_Updated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Monthly_Points")
                        .HasColumnType("int");

                    b.Property<int>("Student_ID")
                        .HasColumnType("int");

                    b.Property<int>("Total_Points")
                        .HasColumnType("int");

                    b.HasKey("Point_ID");

                    b.HasIndex("Student_ID");

                    b.HasIndex("Total_Points");

                    b.ToTable("TblStudentPoints");
                });

            modelBuilder.Entity("SalesModel.Models.TblAttendance", b =>
                {
                    b.Property<int>("Attendance_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Attendance_ID"));

                    b.Property<DateTime?>("Attendance_AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Attendance_AddUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Attendance_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Attendance_DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Attendance_DeleteUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Attendance_EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Attendance_EditUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Attendance_LateMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Attendance_Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Attendance_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Attendance_Time")
                        .HasColumnType("time");

                    b.Property<string>("Attendance_Visible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Student_ID")
                        .HasColumnType("int");

                    b.HasKey("Attendance_ID");

                    b.HasIndex("Student_ID");

                    b.ToTable("TblAttendance");
                });

            modelBuilder.Entity("SalesModel.Models.TblBranch", b =>
                {
                    b.Property<int>("Branch_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Branch_ID"));

                    b.Property<DateTime?>("Branch_AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Branch_AddUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Branch_DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Branch_DeleteUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Branch_EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Branch_EditUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch_Visible")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Branch_ID");

                    b.ToTable("TblBranch");
                });

            modelBuilder.Entity("SalesModel.Models.TblClass", b =>
                {
                    b.Property<int>("Class_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Class_ID"));

                    b.Property<DateTime?>("Class_AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Class_AddUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Class_DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Class_DeleteUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Class_EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Class_EditUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class_Visible")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Class_ID");

                    b.ToTable("TblClass");
                });

            modelBuilder.Entity("SalesModel.Models.TblClassRoom", b =>
                {
                    b.Property<int>("ClassRoom_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassRoom_ID"));

                    b.Property<DateTime?>("ClassRoom_AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClassRoom_AddUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ClassRoom_DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClassRoom_DeleteUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ClassRoom_EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClassRoom_EditUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassRoom_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassRoom_Visible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Class_ID")
                        .HasColumnType("int");

                    b.HasKey("ClassRoom_ID");

                    b.HasIndex("Class_ID");

                    b.ToTable("TblClassRoom");
                });

            modelBuilder.Entity("SalesModel.Models.TblProduct_Category", b =>
                {
                    b.Property<int>("ProductCategory_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductCategory_ID"));

                    b.Property<DateTime?>("ProductCategory_AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductCategory_AddUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProductCategory_DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductCategory_DeleteUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProductCategory_EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductCategory_EditUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductCategory_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductCategory_Visible")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductCategory_ID");

                    b.ToTable("TblProduct_Category");
                });

            modelBuilder.Entity("SalesModel.Models.TblSchoolSettings", b =>
                {
                    b.Property<int>("Setting_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Setting_ID"));

                    b.Property<DateTime?>("Setting_AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Setting_AddUserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Setting_DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Setting_DeleteUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Setting_Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Setting_EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Setting_EditUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Setting_Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Setting_Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Setting_Visible")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Setting_ID");

                    b.ToTable("TblSchoolSettings");
                });

            modelBuilder.Entity("SalesModel.Models.TblStudent", b =>
                {
                    b.Property<int>("Student_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Student_ID"));

                    b.Property<int>("ClassRoom_ID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Student_AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Student_AddUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Student_BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Student_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Student_DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Student_DeleteUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Student_EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Student_EditUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student_Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student_Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student_Visible")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Student_ID");

                    b.HasIndex("ClassRoom_ID");

                    b.ToTable("TblStudent");
                });

            modelBuilder.Entity("SalesModel.Models.TblVat", b =>
                {
                    b.Property<int>("VatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VatID"));

                    b.Property<double>("VatPercent")
                        .HasColumnType("float");

                    b.Property<double>("VatValue")
                        .HasColumnType("float");

                    b.HasKey("VatID");

                    b.ToTable("TblVat");
                });

            modelBuilder.Entity("SalesModel.Models.ApplicationRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.HasDiscriminator().HasValue("ApplicationRole");
                });

            modelBuilder.Entity("SalesModel.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<int>("Branch_ID")
                        .HasColumnType("int");

                    b.Property<int>("CashBalanceBank_ID")
                        .HasColumnType("int");

                    b.Property<int>("CashBalance_ID")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Visible")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("Branch_ID");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SalesModel.Models.StudentBadge", b =>
                {
                    b.HasOne("SalesModel.Models.TblStudent", "Student")
                        .WithMany()
                        .HasForeignKey("Student_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SalesModel.Models.StudentPoints", b =>
                {
                    b.HasOne("SalesModel.Models.TblStudent", "Student")
                        .WithMany()
                        .HasForeignKey("Student_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SalesModel.Models.TblAttendance", b =>
                {
                    b.HasOne("SalesModel.Models.TblStudent", "Student")
                        .WithMany()
                        .HasForeignKey("Student_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SalesModel.Models.TblClassRoom", b =>
                {
                    b.HasOne("SalesModel.Models.TblClass", "Class")
                        .WithMany("ClassRooms")
                        .HasForeignKey("Class_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("SalesModel.Models.TblStudent", b =>
                {
                    b.HasOne("SalesModel.Models.TblClassRoom", "ClassRoom")
                        .WithMany("Students")
                        .HasForeignKey("ClassRoom_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassRoom");
                });

            modelBuilder.Entity("SalesModel.Models.ApplicationUser", b =>
                {
                    b.HasOne("SalesModel.Models.TblBranch", "TblBranch")
                        .WithMany()
                        .HasForeignKey("Branch_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TblBranch");
                });

            modelBuilder.Entity("SalesModel.Models.TblClass", b =>
                {
                    b.Navigation("ClassRooms");
                });

            modelBuilder.Entity("SalesModel.Models.TblClassRoom", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
